#!/usr/bin/bash

if [ $# -eq 0 ]; then
  echo "Enter your commit message. [CTRL+D] to confirm, [CTRL+C] to cancel."
  COMMIT_MSG=$(</dev/stdin)
else
  COMMIT_MSG="$@"
fi

git add --all && \
git stage --all && \
git commit -m $"$COMMIT_MSG"

exit 0
